### ISSUE TITLE
Racket 8.4: How should your name appear in the release notes?

### ISSUE THREAD

**Issue by jbclements** [rgkirch/dotfiles#1]
I apologize for this admittedly semi-abusive use of an issue as a means of contacting you.

You’re one of the list of contributors to the 8.4 release. Thanks very much! I’m wondering how your name should appear. Currently, my best guess is 

rgkirch

Does that look right to you?

Feel free to contact me at aoeugithub@brinckerhoff.org

Many thanks,

John Clements

**Comment by rgkirch** [comment]
Haha, no trouble.
This is quite unexpected.
rgkirch is fine, thank you!

**Comment by jbclements** [comment]
Done!

Best,

John Clements
